In [22]:
# Dependencies
import numpy as np
import datetime as dt
import pandas as pd

# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

In [10]:
engine = create_engine("sqlite:///hawaii.sqlite")

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

print(Base.classes.keys())


# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

['measurement', 'station']

In [11]:
# Create our session (link) from Python to the DB
session = Session(engine)

## D1: Determine the Summary Statistics for June

In [24]:
# 1. Import the sqlalchemy extract function.
from sqlalchemy import extract

# 2. Write a query that filters the Measurement table to retrieve the temperatures for the month of June.
first_date = dt.date(2017, 6, 1)
last_date = dt.date(2017, 6, 1) + dt.timedelta(days=30)

session.query(Measurement.date, Measurement.tobs).filter(Measurement.date >= first_date).\
    filter(Measurement.date <= last_date).\
    order_by(Measurement.date).all()

[('2017-06-01', 79.0),
 ('2017-06-01', 76.0),
 ('2017-06-01', 81.0),
 ('2017-06-01', 79.0),
 ('2017-06-01', 80.0),
 ('2017-06-01', 74.0),
 ('2017-06-02', 79.0),
 ('2017-06-02', 76.0),
 ('2017-06-02', 78.0),
 ('2017-06-02', 79.0),
 ('2017-06-02', 81.0),
 ('2017-06-02', 76.0),
 ('2017-06-03', 79.0),
 ('2017-06-03', 76.0),
 ('2017-06-03', 80.0),
 ('2017-06-03', 79.0),
 ('2017-06-03', 76.0),
 ('2017-06-03', 74.0),
 ('2017-06-04', 79.0),
 ('2017-06-04', 78.0),
 ('2017-06-04', 79.0),
 ('2017-06-04', 81.0),
 ('2017-06-04', 77.0),
 ('2017-06-04', 77.0),
 ('2017-06-05', 80.0),
 ('2017-06-05', 76.0),
 ('2017-06-05', 81.0),
 ('2017-06-05', 78.0),
 ('2017-06-05', 78.0),
 ('2017-06-05', 75.0),
 ('2017-06-05', 74.0),
 ('2017-06-06', 79.0),
 ('2017-06-06', 75.0),
 ('2017-06-06', 80.0),
 ('2017-06-06', 80.0),
 ('2017-06-06', 78.0),
 ('2017-06-06', 75.0),
 ('2017-06-06', 74.0),
 ('2017-06-07', 79.0),
 ('2017-06-07', 75.0),
 ('2017-06-07', 81.0),
 ('2017-06-07', 80.0),
 ('2017-06-07', 78.0),
 ('2017-06-07', 75.0),
 ('2017-06-07', 79.0),
 ('2017-06-08', 80.0),
 ('2017-06-08', 76.0),
 ('2017-06-08', 79.0),
 ('2017-06-08', 78.0),
 ('2017-06-08', 77.0),
 ('2017-06-08', 75.0),
 ('2017-06-08', 75.0),
 ('2017-06-09', 80.0),
 ('2017-06-09', 78.0),
 ('2017-06-09', 81.0),
 ('2017-06-09', 80.0),
 ('2017-06-09', 78.0),
 ('2017-06-09', 72.0),
 ('2017-06-10', 77.0),
 ('2017-06-10', 75.0),
 ('2017-06-10', 78.0),
 ('2017-06-10', 75.0),
 ('2017-06-10', 74.0),
 ('2017-06-10', 72.0),
 ('2017-06-11', 79.0),
 ('2017-06-11', 73.0),
 ('2017-06-11', 79.0),
 ('2017-06-11', 81.0),
 ('2017-06-11', 74.0),
 ('2017-06-11', 76.0),
 ('2017-06-12', 83.0),
 ('2017-06-12', 76.0),
 ('2017-06-12', 79.0),
 ('2017-06-12', 80.0),
 ('2017-06-12', 74.0),
 ('2017-06-12', 74.0),
 ('2017-06-13', 80.0),
 ('2017-06-13', 76.0),
 ('2017-06-13', 75.0),
 ('2017-06-13', 81.0),
 ('2017-06-13', 77.0),
 ('2017-06-13', 76.0),
 ('2017-06-13', 73.0),
 ('2017-06-14', 80.0),
 ('2017-06-14', 76.0),
 ('2017-06-14', 79.0),
 ('2017-06-14', 78.0),
 ('2017-06-14', 80.0),
 ('2017-06-14', 74.0),
 ('2017-06-14', 74.0),
 ('2017-06-15', 78.0),
 ('2017-06-15', 77.0),
 ('2017-06-15', 78.0),
 ('2017-06-15', 77.0),
 ('2017-06-15', 78.0),
 ('2017-06-15', 75.0),
 ('2017-06-15', 77.0),
 ('2017-06-16', 79.0),
 ('2017-06-16', 76.0),
 ('2017-06-16', 80.0),
 ('2017-06-16', 78.0),
 ('2017-06-16', 80.0),
 ('2017-06-16', 73.0),
 ('2017-06-16', 74.0),
 ('2017-06-17', 80.0),
 ('2017-06-17', 77.0),
 ('2017-06-17', 78.0),
 ('2017-06-17', 77.0),
 ('2017-06-17', 79.0),
 ('2017-06-17', 72.0),
 ('2017-06-18', 77.0),
 ('2017-06-18', 72.0),
 ('2017-06-18', 77.0),
 ('2017-06-18', 78.0),
 ('2017-06-18', 75.0),
 ('2017-06-18', 77.0),
 ('2017-06-19', 80.0),
 ('2017-06-19', 77.0),
 ('2017-06-19', 78.0),
 ('2017-06-19', 78.0),
 ('2017-06-19', 78.0),
 ('2017-06-19', 72.0),
 ('2017-06-19', 76.0),
 ('2017-06-20', 78.0),
 ('2017-06-20', 75.0),
 ('2017-06-20', 79.0),
 ('2017-06-20', 77.0),
 ('2017-06-20', 72.0),
 ('2017-06-20', 74.0),
 ('2017-06-21', 79.0),
 ('2017-06-21', 82.0),
 ('2017-06-21', 76.0),
 ('2017-06-21', 80.0),
 ('2017-06-21', 74.0),
 ('2017-06-21', 75.0),
 ('2017-06-22', 80.0),
 ('2017-06-22', 77.0),
 ('2017-06-22', 81.0),
 ('2017-06-22', 80.0),
 ('2017-06-22', 72.0),
 ('2017-06-22', 76.0),
 ('2017-06-23', 78.0),
 ('2017-06-23', 76.0),
 ('2017-06-23', 76.0),
 ('2017-06-23', 76.0),
 ('2017-06-23', 79.0),
 ('2017-06-23', 72.0),
 ('2017-06-23', 71.0),
 ('2017-06-24', 80.0),
 ('2017-06-24', 74.0),
 ('2017-06-24', 82.0),
 ('2017-06-24', 77.0),
 ('2017-06-24', 73.0),
 ('2017-06-25', 80.0),
 ('2017-06-25', 73.0),
 ('2017-06-25', 80.0),
 ('2017-06-25', 71.0),
 ('2017-06-25', 79.0),
 ('2017-06-26', 81.0),
 ('2017-06-26', 77.0),
 ('2017-06-26', 80.0),
 ('2017-06-26', 82.0),
 ('2017-06-26', 81.0),
 ('2017-06-26', 73.0),
 ('2017-06-26', 79.0),
 ('2017-06-27', 80.0),
 ('2017-06-27', 77.0),
 ('2017-06-27', 80.0),
 ('2017-06-27', 81.0),
 ('2017-06-27', 76.0),
 ('2017-06-27', 74.0),
 ('2017-06-28', 79.0),
 ('2017-06-28', 77.0),
 ('2017-06-28', 80.0),
 ('2017-06-28', 79.0),
 ('2017-06-28', 77.0),
 ('2017-06-28', 74.0),
 ('2017-06-29', 79.0),
 ('2017-06-29', 76.0),
 ('2017-06-29', 76.0),
 ('2017-06-29', 79.0),
 ('2017-06-29', 78.0),
 ('2017-06-29', 76.0),
 ('2017-06-29', 76.0),
 ('2017-06-30', 75.0),
 ('2017-06-30', 74.0),
 ('2017-06-30', 81.0),
 ('2017-06-30', 74.0),
 ('2017-06-30', 75.0),
 ('2017-06-30', 76.0),
 ('2017-06-30', 75.0),
 ('2017-07-01', 80.0),
 ('2017-07-01', 76.0),
 ('2017-07-01', 79.0),
 ('2017-07-01', 74.0)]

In [25]:
#  3. Convert the June temperatures to a list.
results = []
results = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date >= first_date).\
    filter(Measurement.date <= last_date).all()

In [28]:
# 4. Create a DataFrame from the list of temperatures for the month of June. 
df = pd.DataFrame(results, columns=['date','temperature'])
df.set_index(df['date'], inplace=True)
df

           date  temperature
0    2017-06-01         79.0
1    2017-06-02         79.0
2    2017-06-03         79.0
3    2017-06-04         79.0
4    2017-06-05         80.0
..          ...          ...
190  2017-06-27         74.0
191  2017-06-28         74.0
192  2017-06-29         76.0
193  2017-06-30         75.0
194  2017-07-01         74.0

[195 rows x 2 columns]

In [7]:
# 5. Calculate and print out the summary statistics for the June temperature DataFrame.

## D2: Determine the Summary Statistics for December

In [8]:
# 6. Write a query that filters the Measurement table to retrieve the temperatures for the month of December.

In [9]:
# 7. Convert the December temperatures to a list.

In [10]:
# 8. Create a DataFrame from the list of temperatures for the month of December.

In [11]:
# 9. Calculate and print out the summary statistics for the Decemeber temperature DataFrame.